### ISSUE TITLE
a little question

### ISSUE THREAD

**Issue by eyuansu62** [AIPHES/emnlp19-moverscore#5]
You mentioned you fine-tuned the Bert model on some NLI tasks, and then used its model to embedded the sentences. But the code you released did not contain the related code and fine-tuned Bert model, right?

**Comment by andyweizhao** [comment]
I did release the BERT model fine-tuned on NLI. Please check out line 24 and line 65 in moverscore.py, but I did not release the code about how to fine-tune BERT because you can find it in https://github.com/huggingface/transformers.

**Comment by eyuansu62** [comment]
Oh, i see, thank you!!
And in "model = BertForSequenceClassification.from_pretrained(output_dir, 3)", you set the labels=3, why the label is set to 3?

**Comment by andyweizhao** [comment]
MNLI corpus has three labels: neutral, contradiction and entailment.

**Comment by eyuansu62** [comment]
Oh, i understand!
Really really thanks!!!

**Comment by eyuansu62** [comment]
hi，can I ask you another question ？
Why the the score obtained by end is always between 0 and 1, except for those informal cases？
It is very kind for your reply



---Original---
