### ISSUE TITLE
why the score you compute using emd function is always between 0 and 1? Does it contain some normalization process?

### ISSUE THREAD

**Issue by eyuansu62** [AIPHES/emnlp19-moverscore#8]

**Comment by andyweizhao** [comment]
Indeed, one can see negative values returning from that python package, meaning that the final score is not normalized.

**Comment by eyuansu62** [comment]
Thanks for your reply, may i can ask another question?
where can i find the file DA-seglevel.csv mentioned in output_MT_correlation, which i mean its original version, and why the correlation just uses around 500 sentences for each "system"?
It will be great helpful if you can answer me this question.
And 我也是杨敏老师的学生,请问能加一个学长的联系方式嘛

**Comment by andyweizhao** [comment]
where can i find the file DA-seglevel.csv mentioned in
output_MT_correlation, which i mean its original version, and why the
correlation just uses around 500 sentences for each "system"?

-- Check out more information in MT evaluation metrics:
http://www.statmt.org/wmt17/metrics-task.html. Also, see l.17 in
mt_utils.py where I have packed all data used in MT evaluation.

我也是杨敏老师的学生,请问能加一个学长的联系方式嘛
My WeChat: NATHANIEL3894

Best,
Wei

**Comment by andyweizhao** [comment]
1. Check out more information in MT evaluation metrics: http://www.statmt.org/wmt17/metrics-task.html 2. See l.17 in mt_utils.py where I have packed all data used in MT evaluation
3. The test set in WMT17 metrics shared task is about 560 for each language pair.

**Comment by andyweizhao** [comment]
1. Check out more information in MT evaluation metrics: http://www.statmt.org/wmt17/metrics-task.html 
2. See l.17 in mt_utils.py where I have packed all data used in MT evaluation
3. The test set in WMT17 metrics shared task is about 560 for each language pair.

**Comment by andyweizhao** [comment]
You can reach out to me by email for additional questions (andyweizhao1@gmail.com)

**Comment by eyuansu62** [comment]
really really thanks😁😁



---Original---
